### ISSUE TITLE
1.18.2 error 

### ISSUE THREAD

**Issue by SilverRedKahemane** [freethemice/TitanTelePads#1]
hi, the plugin is no working on 1.18.2 :c i got this error

https://pastebin.com/AyFQ9m8v

**Comment by SilverRedKahemane** [comment]
> hi, the plugin is no working on 1.18.2 :c i got this error
> 
> https://pastebin.com/AyFQ9m8v

i got the lastest version of TitanTelePads and TitanBoxLib

**Comment by freethemice** [comment]
this will be fixed on next release, should be today or tomorrow.

**Comment by SilverRedKahemane** [comment]
ok tysm
