### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SilverRedKahemane** [freethemice/TitanTelePads#2]
hello, there is an error, I get this in the console, I don't know what generates it, but it doesn't let me use the telepads, when I place them on the ground they don't appear in the GUI

https://pastebin.com/1MYLqSuE

**Comment by freethemice** [comment]
this version should fix it, let me know if it works
https://github.com/freethemice/TitanTelePads/releases/tag/1.5.5

**Comment by SilverRedKahemane** [comment]
is working perfect now, TYSM!!! <3
