### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Twilight0Sparkle** [freethemice/TitanTelePads#3]
1) When you break the teleport - it sometimes stays in place and you need to kill the armor stand
2) Make it so that you can translate the plugin into another language and put a black glass panel instead of the grass in the GUI

**Comment by project234534** [comment]
When you break the teleport - it sometimes stays in place and you need to kill the armor stand 
make a command that remove it 
and make a setting so ju can set off or on the hologram

**Comment by freethemice** [comment]
This should be fix in 1.6.1. Also added the command "/tep remove <holograms/armorstands> <all/distance>". Also, added the language file, please fill free to send me new language files for public use
