### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fly805** [freethemice/TitanTelePads#4]
![image](https://github.com/freethemice/TitanTelePads/assets/138732949/8b31d887-308f-4239-9293-ffc763688381)

This happend when i type 
/tep give [my name]

**Comment by freethemice** [comment]
do you have the console log, or the error it send to console?

**Comment by freethemice** [comment]
This appears to be from an older version, please update to the newest version and if the error counties repost with console log or error from console thank you.
